### ISSUE TITLE
Hot-replacement of reducers

### ISSUE THREAD

**Issue by wcjohnson** [wcjohnson/redux-components#5]
Split from #4 

There's no way to do this *without* creating state that's not a part of the store, because fundamentally, a reducer is a function and a function can't be state.

However, as you pointed out, if the state that's not a part of the store is a pure function of the state that is, and we can guarantee it gets synced with the store, that should still be OK.

So here are my thoughts right now:

- `getReducer()` is now passed the local `state` as an argument. When first mounting, this will be the initial state. So:

```coffeescript
getReducer: (state) => (state,action) => nextState
``` 

- A new action symbol, `@@REPLACE_REDUCER`, will be added.

- The actual reducer produced by Redux Components internally, the one that really gets mounted to the state tree, will be a closure that has an additional layer of indirection, and when it gets the `@@REPLACE_REDUCER` action, it will hot swap the "real" reducer by calling `getReducer()`.

Advantages:

- DOES NOT require the root store to rebuild its reducer!

- State, in toto, is still a pure function of Redux state. `getReducer()` is only receiving information that already is in the store.

- This doesn't just enable the thing we're talking about here, but a huge range of behaviors where reducers can depend purely on state.

Disadvantages:

- Appears to absolutely require impurity in the intermediate layer of reducer indirection. How do we respond to `@@REPLACE_REDUCER` purely?

- Performance hit of one extra nested function call for each layer of Redux state tree depth. (Won't matter when JS finally implements proper tailcalls -- probably won't matter before that, even.)

Things that need to be tested intensively:

- Store initialization and rehydration situations

- **TIME TRAVEL**

**Comment by Diggsey** [comment]
Great :) And by taking a closure for `type_map`, it can work as a generic, use a discriminator, look up a type name in a global map, or any other method of constructing a type from state, completely avoiding the type map issue you mentioned before.

**Comment by wcjohnson** [comment]
I remember why I didn't release this before. Reasoning about meta-Redux gets to be like Alice in Wonderland.

Just making notes to myself here:
- The approach above is actually a non-starter. At some point, a component like `Map` is going to have to call `componentWillMount` on the subcomponents. With the approach above as written, `componentWillMount` ends up being called as a _side-effect_ inside of a reducer. This is disastrous, because `componentWillMount` is not only not a pure function, it's the opposite of a pure function. It's designed to have further side effects. INCLUDING possibly dispatching actions to the store. Including possibly actions that would mutate the `Map` itself!
  
  That means that users will almost certainly wind up accidentally breaking Redux's contract, and triggering the `dispatch` within `dispatch` exception.
  
  Someday I will learn to NEVER make reducers with side effects, even if it seems innocent at the time.
- So, next approach needs to maintain reducer purity.
- Also, probably need a development-mode reentrancy guard, because regardless of how we do this, we can't have the `Map` mutator algorithm synchronously calling a function that would mutate the `Map` again.

So, approach #2:

## Observable selector

The idea is to mutate the component hierarchy whenever the `Map`'s metadata is mutated. We could do this outside of the reducer chain, maintaining purity, by making a selector on `state.__metadata` and watching it for changes.

The observer attached to the selector _is_ allowed to have side effects, and therefore we diff the `Map`'s tree against the desired tree inside the observer, calling all the `willMount`'s and `willUnmounts` as needed.

_Then_ we call `getReducer()` to hot swap the reducer; this is all running synchronously after the end of the `dispatch()` call that mutated the metadata, so we are guaranteed not to step on any running reducers.

So, next approach:
- No new action token.
- API change to `getReducer()` remains the same.
- Still need a layer of reducer indirection.
- `componentWillMount` for `Map` will attach an observer to a selector on `state.__metadata`
- Selector will call `map.diff()` which will actually diff the keys
- Probably use deep equal with the observer to ignore insignificant metadata changes. Don't expect metadata to change very frequently.

Advantages:
- Actually pure reducer
- Should still work with time travel (time traveling the store will cause the observer to see the new metadata immediately and trigger)
- Should work with rehydration (observable will call the observer on startup just as the Redux core version does)

Disadvantages:
- Still probably need reentrancy check in the diffing algorithm. We don't want the `Map` mutating itself while mutating because of a side effect

## Further design questions
- Should `Map` support `.set` on an existing item in the map? What would this mean? Is it equivalent to `remove` followed by `add`, i.e. would it unmount the component and then remount the replacement?
  
  I was thinking maybe it should not be implemented at all if this is the case. User might expect it to mutate a component in place somehow, without dismouting it. Redux-components is not designed to work that way; if you want to mutate something about a component you are supposed to do it through Redux actions.
  
  Therefore, rather than implementing `.set`, let user call `.remove` followed by `.add` himself so he knows what is happening.

**Comment by wcjohnson** [comment]
Just thought of another nightmare scenario:
- `Map` metadata changes, triggering the observer.
- The diff algorithm determines a new component needs to be mounted.
- Before its reducer can be attached to the tree, according to ReduxComponents contract, It is created and `componentWillMount` is called with its initial state.
- Let's say `componentWillMount` dispatches an action (ANY action at all) which it is allowed to do because it is a place to put your side effects.
- This is a disaster because dispatching any action will call reducers. But the new component's reducer hasn't been mounted yet since `willMount` runs before reducer installation. So the stale  `combineReducers()` reducer, which does not know there is a subcomponent there, will simply **DROP THE SUBCOMPONENT'S STATE FROM THE TREE!**

In fact, this may be a bug in the current `SubtreeMixin` as well, which goes un noticed because all users are just using the static Subtrees are initialized at boot time.

So, how to get around this? Maybe something like this:
- Diff the current component tree node with the metadata. Build an `added` and `removed` list.
- Don't delete the `removed` nodes from the state tree yet, because we haven't called `willUnmount` on them. Mount a _temporary_ reducer using `combineReducers()` but with the identity function attached at each `added` node.
- Run `componentWillUnmount` for each `removed` node that is a ReduxComponent.
- Run `componentWillMount` for each `added` node that is a ReduxComponent.
- Now build the _real_ reducer from `getReducer()` on each component + `combineReducers()`. All the `added` nodes are added with their correct reducers and the `removed` nodes are no longer mounted.
- Run `componentDidMount` for each `added` component.

**Comment by wcjohnson** [comment]
This stuff has all been implemented in @0.2.1. The map component is a separate library, [redux-components-map](https://github.com/wcjohnson/redux-components-map)
